name: Dispatch Merge (Project 1)

on:
  workflow_run:
    workflows: ["Build and Push (Project 1)"]
    types: [completed]

jobs:
  dispatch:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger orchestrator merge
        env:
          GH_PAT: ${{ secrets.ORCH_PAT }}
          ORCH_OWNER: ${{ github.repository_owner }}
          ORCH_REPO: Supervisor-Image-Combination
          SA_REPO: ${{ github.repository_owner }}/project-1
          SA_REF: main
          SA_DOCKERFILE: Dockerfile
          SB_REPO: ${{ github.repository_owner }}/project-2
          SB_REF: main
          SB_DOCKERFILE: Dockerfile
        run: |
          if [ -z "$GH_PAT" ]; then echo "ORCH_PAT secret missing; skipping dispatch"; exit 0; fi
          curl -s -X POST \
           -H "Authorization: token ${GH_PAT}" \
           -H "Accept: application/vnd.github+json" \
           https://api.github.com/repos/${ORCH_OWNER}/${ORCH_REPO}/dispatches \
           -d "{\"event_type\":\"project-updated\",\"client_payload\":{\"service_a_repo\":\"${SA_REPO}\",\"service_a_ref\":\"${SA_REF}\",\"service_a_dockerfile\":\"${SA_DOCKERFILE}\",\"service_b_repo\":\"${SB_REPO}\",\"service_b_ref\":\"${SB_REF}\",\"service_b_dockerfile\":\"${SB_DOCKERFILE}\",\"use_gpu_base\":false}}"
